2024-11-22 22:30:38,856 - INFO - Connected to RabbitMQ
2024-11-22 22:30:38,956 - INFO - Server is listening on queue: bews
2024-11-22 22:30:38,957 - INFO - Server is running. Press Ctrl+C to stop.
2024-11-22 22:30:43,766 - INFO - Received Request: ID=04a3a833-e4c1-4e6b-a3f2-edbba07c2b46, Request=23
2024-11-22 22:30:43,766 - INFO - Processed request: 23 -> Response: 46
2024-11-22 22:30:50,885 - INFO - Received Request: ID=1d5b5bb0-5577-4e94-81b3-01939bfa3675, Request=144
2024-11-22 22:30:50,886 - INFO - Processed request: 144 -> Response: 288
2024-11-22 22:30:57,975 - INFO - Received Request: ID=0bfbaf8e-b8ce-46c3-a0d4-984fe2897d88, Request=145
2024-11-22 22:30:57,977 - INFO - Processing request with delay of 10.0 seconds
2024-11-22 22:30:59,343 - ERROR - Exception in callback _task_done(<Task finishe...dStateError()>) at Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\tools.py:43
handle: <Handle _task_done(<Task finishe...dStateError()>) at Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\tools.py:43>
Traceback (most recent call last):
  File "C:\Users\danii\Desktop\GUI\server\rabbitmq_server\__main__.py", line 23, in handle_request
    await asyncio.sleep(req.process_time_in_seconds)
  File "Z:\conda\envs\pyqt-env\Lib\asyncio\tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\conda\envs\pyqt-env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\tools.py", line 47, in _task_done
    raise exc
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\tools.py", line 288, in wrapper
    return await result
           ^^^^^^^^^^^^
  File "C:\Users\danii\Desktop\GUI\server\rabbitmq_server\__main__.py", line 12, in handle_request
    async with message.process():
               ^^^^^^^^^^^^^^^^^
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\message.py", line 582, in __aexit__
    if not self.message.channel.is_closed:
           ^^^^^^^^^^^^^^^^^^^^
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\aio_pika\message.py", line 391, in channel
    raise ChannelInvalidStateError
aiormq.exceptions.ChannelInvalidStateError
2024-11-22 23:21:29,301 - INFO - Connected to RabbitMQ
2024-11-22 23:21:29,385 - INFO - Server is listening on queue: bews
2024-11-22 23:21:29,385 - INFO - Server is running. Press Ctrl+C to stop.
2024-11-22 23:21:32,158 - INFO - Received Request: ID=cd410d00-fa67-4623-a9bd-3027c555efb7, Request=14
2024-11-22 23:21:32,159 - INFO - Processing request with delay of 4.0 seconds
2024-11-22 23:21:36,172 - INFO - Processed request: 14 -> Response: 28
2024-11-22 23:28:38,761 - INFO - Connected to RabbitMQ
2024-11-22 23:28:38,834 - INFO - Server is listening on queue: bews
2024-11-22 23:28:38,835 - INFO - Server is running. Press Ctrl+C to stop.
2024-11-22 23:28:43,838 - INFO - Received Request: ID=416f17ab-b058-4ad1-be27-4176ee5ec15c, Request=2
2024-11-22 23:28:43,838 - INFO - Processed request: 2 -> Response: 4
2024-11-22 23:28:49,891 - INFO - Received Request: ID=5cfbfb7c-f2b1-44f1-9432-52527f1cd9fe, Request=3
2024-11-22 23:28:49,892 - INFO - Processed request: 3 -> Response: 6
2024-11-22 23:29:33,710 - INFO - Received Request: ID=73854331-6dda-4962-9323-df3c683d76e1, Request=23
2024-11-22 23:29:33,710 - INFO - Processed request: 23 -> Response: 46
2024-11-22 23:31:32,227 - INFO - Received Request: ID=ddc965b2-2d4a-472a-b1fa-f38a1385ed79, Request=32
2024-11-22 23:31:32,228 - INFO - Processed request: 32 -> Response: 64
2024-11-22 23:31:52,856 - INFO - Received Request: ID=2b510d11-a082-45d4-935a-28ada6a19c23, Request=32
2024-11-22 23:31:52,857 - INFO - Processed request: 32 -> Response: 64
2024-11-22 23:35:56,331 - INFO - Received Request: ID=2adc6585-ade1-49fb-b983-fd70121bcc52, Request=32
2024-11-22 23:35:56,331 - INFO - Processed request: 32 -> Response: 64
2024-11-22 23:36:03,381 - INFO - Received Request: ID=9142f30b-aeaa-4923-be4c-df5b7b591923, Request=32
2024-11-22 23:36:03,381 - INFO - Processing request with delay of 23.0 seconds
2024-11-22 23:36:20,505 - INFO - Received Request: ID=415ce7c3-6b97-45c7-bf12-db22f69ec52a, Request=11
2024-11-22 23:36:20,506 - INFO - Processing request with delay of 2.0 seconds
2024-11-22 23:36:22,510 - INFO - Processed request: 11 -> Response: 22
2024-11-22 23:36:26,398 - INFO - Processed request: 32 -> Response: 64
2024-11-22 23:38:15,468 - INFO - Received Request: ID=f86009eb-62f9-4c0f-b305-53b1d2c62423, Request=223
2024-11-22 23:38:15,468 - INFO - Processing request with delay of 2.0 seconds
2024-11-22 23:38:17,483 - INFO - Processed request: 223 -> Response: 446
2024-11-22 23:38:35,457 - INFO - Received Request: ID=babd1e25-0e6b-4353-b746-f8599d215b77, Request=23
2024-11-22 23:38:35,457 - INFO - Processed request: 23 -> Response: 46
2024-11-22 23:39:15,696 - INFO - Received Request: ID=ff208d50-65d8-4b6b-b108-9fee6c7e7639, Request=2
2024-11-22 23:39:15,697 - INFO - Processed request: 2 -> Response: 4
2024-11-22 23:40:13,535 - INFO - Received Request: ID=695c1a98-227c-445c-9adc-6ede3a73359f, Request=32
2024-11-22 23:40:13,535 - INFO - Processed request: 32 -> Response: 64
