2024-10-24 17:21:10 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-24 17:21:10 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37218), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:10 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7463c4cc34f0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7463c4cc34f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-24 17:21:10 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7463c4cc34f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:10 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7463c4cc34f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:10 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7463c4cc34f0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:10 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-24 17:21:10 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-QPOxmjyuAf78UM3VZS2ErA
2024-10-24 17:21:10 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-24 17:21:10 - INFO - client: Received response: Hello for request ID: eee22e44-8854-4b6b-9b75-bc3b598208d5
2024-10-24 17:21:10 - INFO - client: Server is ready.
2024-10-24 17:21:14 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37218), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-24 17:21:14 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37218), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:14 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37218), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:14 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:14 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-24 17:21:14 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:14 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37218), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:14 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:14 - ERROR - client: Error sending request: Stream connection lost: IndexError('pop from an empty deque')
2024-10-24 17:21:14 - ERROR - client: Failed to connect to RabbitMQ: 'NoneType' object has no attribute 'clear'
2024-10-24 17:21:18 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-24 17:21:18 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37226), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:18 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x754d940b74c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x754d940b74c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-24 17:21:18 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x754d940b74c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:18 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x754d940b74c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:18 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x754d940b74c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:18 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-24 17:21:18 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-Oj6NvpMlm_08Q8tiQpUdbA
2024-10-24 17:21:18 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-24 17:21:18 - INFO - client: Received response: Hello for request ID: 24aaae1f-2e5e-4624-b64f-badf82877302
2024-10-24 17:21:18 - INFO - client: Server is ready.
2024-10-24 17:21:19 - INFO - client: Sent request: 23
2024-10-24 17:21:20 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37226), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-24 17:21:20 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37226), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:20 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37226), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:20 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:20 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-24 17:21:20 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:20 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37226), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:20 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:20 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-24 17:21:20 - ERROR - client: Failed to connect to RabbitMQ: Timeout closed before call
2024-10-24 17:21:34 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-24 17:21:34 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47258), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:34 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x77e8a5cbada0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x77e8a5cbada0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-24 17:21:34 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x77e8a5cbada0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:34 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x77e8a5cbada0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:34 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x77e8a5cbada0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:34 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-24 17:21:34 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-SZOk45wiVUMlZBciuOhphg
2024-10-24 17:21:34 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-24 17:21:35 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-24 17:21:35 - INFO - client: Received response: Hello for request ID: 2ea351a4-a25d-4dc6-bcb4-eb7a2cbf9999
2024-10-24 17:21:35 - INFO - client: Server is ready.
2024-10-24 17:21:38 - INFO - client: Sent request: 23
2024-10-24 17:21:38 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47258), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-24 17:21:38 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47258), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:38 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47258), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:38 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:38 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-24 17:21:38 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:38 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47258), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:38 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:38 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-24 17:21:38 - ERROR - client: Failed to connect to RabbitMQ: Timeout closed before call
2024-10-24 17:21:47 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-10-24 17:21:47 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47454), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:47 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7cb809cab4c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7cb809cab4c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-10-24 17:21:47 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7cb809cab4c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:47 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7cb809cab4c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:47 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7cb809cab4c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-10-24 17:21:47 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-10-24 17:21:47 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-1XPWgE9ClOooO2kiaBnXWA
2024-10-24 17:21:47 - INFO - client: Sent 'Hi' to server for readiness check.
2024-10-24 17:21:47 - INFO - client: Received response: Hello for request ID: 2a9a459e-5ce1-4cde-9608-5802f6148958
2024-10-24 17:21:47 - INFO - client: Server is ready.
2024-10-24 17:21:50 - INFO - client: Sent request: 23
2024-10-24 17:21:50 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47454), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-10-24 17:21:50 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47454), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:50 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47454), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:50 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:50 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-10-24 17:21:50 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:50 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 47454), raddr=('127.0.0.1', 5672)>
2024-10-24 17:21:50 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-10-24 17:21:50 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-10-24 17:21:50 - ERROR - client: Failed to connect to RabbitMQ: Timeout closed before call
