<<<<<<< HEAD
2024-11-05 22:32:50 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2024-11-05 22:32:52 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=1376, family=23, type=1, proto=6, laddr=('::', 51158, 0, 0)>; error=10061 (Unknown error)
2024-11-05 22:32:52 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0))
2024-11-05 22:32:52 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:32:52 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 22:32:54 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=1376, family=2, type=1, proto=6, laddr=('0.0.0.0', 51161)>; error=10061 (Unknown error)
2024-11-05 22:32:54 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2024-11-05 22:32:54 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:32:54 - ERROR - pika.adapters.utils.connection_workflow: AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error').
2024-11-05 22:32:54 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:32:54 - ERROR - pika.adapters.blocking_connection: Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:32:54 - ERROR - pika.adapters.blocking_connection: Error in _create_connection().
Traceback (most recent call last):
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2024-11-05 22:32:54 - ERROR - client: Failed to connect to RabbitMQ: 
=======
2024-11-05 14:44:38 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 14:44:38 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54496), raddr=('127.0.0.1', 5672)>
2024-11-05 14:44:38 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-05 14:44:38 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 14:44:38 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 14:44:38 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 14:44:38 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-05 14:44:38 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-HJXA4qY8jtlNRCfWck7AdQ
2024-11-05 14:44:38 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 14:44:38 - INFO - client: Received response: PONG for request ID: cb738383-d9b3-428f-9b63-049f9e000dca
2024-11-05 14:44:38 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 14:44:48 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 14:44:51 - INFO - client: Sent request: 23 with delay: 0.0 sec
2024-11-05 14:44:58 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 14:44:58 - WARNING - client: Server heartbeat timed out. Server is considered unavailable.
2024-11-05 14:45:02 - INFO - client: Received response: PONG for request ID: a93929d3-b14f-41a1-86dd-6bb0e036f282
2024-11-05 14:45:02 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 14:45:02 - INFO - client: Received response: 46 for request ID: dce9a040-e836-4215-a4a6-d5e7b8222b6f
2024-11-05 14:45:02 - INFO - client: Received response: PONG for request ID: 13a3e593-47a9-4fca-b388-57f47eda6b74
2024-11-05 14:45:02 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 14:45:08 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 14:45:08 - INFO - client: Received response: PONG for request ID: fea58cc5-7e68-4e75-b4f9-1d850a8e1de6
2024-11-05 14:45:08 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 14:45:11 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-05 14:45:11 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-05 14:45:11 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-05 14:45:11 - CRITICAL - pika.connection: Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bb7dfea4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 14:45:11 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-11-05 14:45:11 - INFO - pika.adapters.utils.io_services_utils: Aborting transport connection: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54496), raddr=('127.0.0.1', 5672)>
2024-11-05 14:45:11 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54496), raddr=('127.0.0.1', 5672)>
2024-11-05 14:45:11 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54496), raddr=('127.0.0.1', 5672)>
2024-11-05 14:45:11 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-11-05 14:45:11 - INFO - pika.connection: Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-11-05 14:45:11 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=3; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54496), raddr=('127.0.0.1', 5672)>
2024-11-05 14:45:11 - INFO - pika.adapters.blocking_connection: User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-11-05 14:45:11 - INFO - client: Connection to RabbitMQ closed.
2024-11-05 14:45:11 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-05 14:45:11 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=4; error=IndexError('pop from an empty deque'); None
2024-11-05 14:45:11 - ERROR - pika.adapters.utils.io_services_utils: Wrapped func exited with exception. Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 14:45:11 - ERROR - pika.adapters.utils.io_services_utils: Wrapped func exited with exception. Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1114, in _on_socket_writable
    self._initiate_abort(error)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1114, in _on_socket_writable
    self._initiate_abort(error)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 14:45:11 - ERROR - client: Unexpected error: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 16:18:23 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 16:18:23 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>
2024-11-05 16:18:23 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-05 16:18:23 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:18:23 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:18:23 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:18:23 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-05 16:18:23 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-cReVZo7vhkBy4Mf_j5OvOA
2024-11-05 16:18:23 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 16:18:23 - INFO - client: Received response: PONG for request ID: 678773ad-c122-471b-bd21-e0b8c15bd946
2024-11-05 16:18:23 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 16:18:32 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-05 16:18:32 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-05 16:18:32 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.cfc09279a3b2416988e3c5ab88d16202'])>"])>
2024-11-05 16:18:32 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>
2024-11-05 16:18:32 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7d60793e2410> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-05 16:18:32 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>
2024-11-05 16:18:32 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:18:32 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-05 16:18:32 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:18:32 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>
2024-11-05 16:18:32 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60500), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-05 16:18:32 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=2; error=IndexError('pop from an empty deque'); <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
2024-11-05 16:18:32 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:18:32 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-05 16:18:32 - ERROR - pika.adapters.utils.io_services_utils: Wrapped func exited with exception. Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 16:18:32 - ERROR - pika.adapters.utils.io_services_utils: Wrapped func exited with exception. Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1114, in _on_socket_writable
    self._initiate_abort(error)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1114, in _on_socket_writable
    self._initiate_abort(error)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 909, in _initiate_abort
    assert self._state != self._STATE_COMPLETED, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 16:18:32 - ERROR - client: Error closing connection: ('_AsyncTransportBase._initate_abort() expected non-_STATE_COMPLETED', 4)
2024-11-05 16:19:57 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 16:19:57 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34882), raddr=('127.0.0.1', 5672)>
2024-11-05 16:19:57 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7c24115ea4a0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7c24115ea4a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-05 16:19:57 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7c24115ea4a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:19:57 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7c24115ea4a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:19:57 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7c24115ea4a0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-05 16:19:57 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-05 16:19:57 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-OVYjiipYS_NdaTcoZ-uM-w
2024-11-05 16:19:57 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-05 16:20:00 - INFO - client: Received response: PONG for request ID: ee146cec-87a1-47ad-bb80-0357bb925b9d
2024-11-05 16:20:00 - INFO - client: Received heartbeat response PONG from server.
2024-11-05 16:20:04 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-05 16:20:04 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34882), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-05 16:20:04 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34882), raddr=('127.0.0.1', 5672)>
2024-11-05 16:20:04 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34882), raddr=('127.0.0.1', 5672)>
2024-11-05 16:20:04 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:20:04 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-05 16:20:04 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:20:04 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34882), raddr=('127.0.0.1', 5672)>
2024-11-05 16:20:04 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-05 16:20:04 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-05 16:20:04 - ERROR - client: Error closing connection: 'NoneType' object has no attribute 'clear'
>>>>>>> d3c6af0a7c94cb7e4a2881f3789a5023355304dc
2024-11-05 22:35:37 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2024-11-05 22:35:39 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=1400, family=23, type=1, proto=6, laddr=('::', 60931, 0, 0)>; error=10061 (Unknown error)
2024-11-05 22:35:39 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0))
2024-11-05 22:35:39 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:35:39 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 22:35:41 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=1400, family=2, type=1, proto=6, laddr=('0.0.0.0', 60935)>; error=10061 (Unknown error)
2024-11-05 22:35:41 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2024-11-05 22:35:41 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:35:41 - ERROR - pika.adapters.utils.connection_workflow: AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error').
2024-11-05 22:35:41 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:35:41 - ERROR - pika.adapters.blocking_connection: Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:35:41 - ERROR - pika.adapters.blocking_connection: Error in _create_connection().
Traceback (most recent call last):
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2024-11-05 22:35:41 - ERROR - client: Failed to connect to RabbitMQ: 
2024-11-05 22:37:27 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2024-11-05 22:37:29 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=992, family=23, type=1, proto=6, laddr=('::', 61050, 0, 0)>; error=10061 (Unknown error)
2024-11-05 22:37:29 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0))
2024-11-05 22:37:29 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:37:29 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-05 22:37:31 - ERROR - pika.adapters.utils.io_services_utils: Socket failed to connect: <socket.socket fd=992, family=2, type=1, proto=6, laddr=('0.0.0.0', 61054)>; error=10061 (Unknown error)
2024-11-05 22:37:31 - ERROR - pika.adapters.utils.connection_workflow: TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2024-11-05 22:37:31 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:37:31 - ERROR - pika.adapters.utils.connection_workflow: AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error').
2024-11-05 22:37:31 - ERROR - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:37:31 - ERROR - pika.adapters.blocking_connection: Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2024-11-05 22:37:31 - ERROR - pika.adapters.blocking_connection: Error in _create_connection().
Traceback (most recent call last):
  File "Z:\conda\envs\pyqt-env\Lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2024-11-05 22:37:31 - ERROR - client: Failed to connect to RabbitMQ: 
2024-11-06 10:49:53 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 10:49:53 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56560), raddr=('127.0.0.1', 5672)>
2024-11-06 10:49:53 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 10:49:53 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:49:53 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:49:53 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:49:53 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 10:49:53 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-YVV2RhAxXPwWmIhLDVpRVA
2024-11-06 10:49:53 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:49:54 - INFO - client: Received response: PONG for request ID: 363afee6-4362-4b92-95ae-b7f89b245e49
2024-11-06 10:49:54 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:04 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:04 - INFO - client: Received response: PONG for request ID: 448706f5-5509-4737-b022-abc8fb05edd7
2024-11-06 10:50:04 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:10 - INFO - client: Sent request: 2313143 with delay: 0.0 sec
2024-11-06 10:50:10 - INFO - client: Received response: 4626286 for request ID: 278dbded-68ee-44f7-a212-78797b9fe3d8
2024-11-06 10:50:14 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:14 - INFO - client: Received response: PONG for request ID: 10ee2ece-bef2-4899-83de-1663b4f369cc
2024-11-06 10:50:14 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:22 - INFO - client: Sent request: 32131313 with delay: 0.0 sec
2024-11-06 10:50:22 - INFO - client: Received response: 64262626 for request ID: 5f01d86d-1ace-42c3-8beb-05df8591be36
2024-11-06 10:50:24 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:24 - INFO - client: Received response: PONG for request ID: 7fc9f2af-fdc8-4d97-a9ca-7dd9eada1785
2024-11-06 10:50:24 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:34 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:34 - INFO - client: Received response: PONG for request ID: d063a0e7-b530-46d0-8561-ce218478749c
2024-11-06 10:50:34 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:38 - INFO - client: Sent request: 423 with delay: 0.0 sec
2024-11-06 10:50:38 - INFO - client: Received response: 846 for request ID: b072c756-a3da-4128-b67e-49e04f836bc3
2024-11-06 10:50:44 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:44 - INFO - client: Received response: PONG for request ID: 9ef57afa-9568-4b94-9556-970536317c75
2024-11-06 10:50:44 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:54 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:50:54 - INFO - client: Received response: PONG for request ID: f2a8e8d7-ab26-4ad4-aa5a-6a947393dd74
2024-11-06 10:50:54 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:50:59 - INFO - client: Sent request: 32131231231232131313123123213124124124124142141243214124124214 with delay: 0.0 sec
2024-11-06 10:50:59 - INFO - client: Received response: 64262462462464262626246246426248248248248284282486428248248428 for request ID: a0020925-1e44-4473-8df2-35ba5952d496
2024-11-06 10:51:04 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:04 - INFO - client: Received response: PONG for request ID: 0465f7bc-1304-490b-98fe-d5b2702dcfbf
2024-11-06 10:51:04 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:14 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:14 - INFO - client: Received response: PONG for request ID: ed0a6a9b-cad8-46ff-87d1-87db396e1fb0
2024-11-06 10:51:14 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:23 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 10:51:23 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34996), raddr=('127.0.0.1', 5672)>
2024-11-06 10:51:23 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x72e6aa9e1270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x72e6aa9e1270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 10:51:23 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x72e6aa9e1270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:51:23 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x72e6aa9e1270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:51:23 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x72e6aa9e1270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:51:23 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 10:51:23 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-rODhUVkGv5gA33tULRUxgA
2024-11-06 10:51:23 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:23 - INFO - client: Received response: PONG for request ID: 0ad8099e-be71-451f-86fc-cf2bbc3078b2
2024-11-06 10:51:23 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:24 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:24 - INFO - client: Received response: PONG for request ID: 7dba7f80-c522-43f4-8864-dc7f4696f0c2
2024-11-06 10:51:24 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:28 - INFO - client: Sent request: 1231312312 with delay: 0.0 sec
2024-11-06 10:51:28 - INFO - client: Received response: 2462624624 for request ID: 93b3f013-8295-4404-ba91-2c2bdf968f83
2024-11-06 10:51:33 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:34 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:40 - INFO - client: Sent request: 2313 with delay: 0.0 sec
2024-11-06 10:51:42 - INFO - client: Sent request: 3123 with delay: 0.0 sec
2024-11-06 10:51:43 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:43 - WARNING - client: Server heartbeat timed out. Server is considered unavailable.
2024-11-06 10:51:44 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:44 - WARNING - client: Server heartbeat timed out. Server is considered unavailable.
2024-11-06 10:51:50 - INFO - client: Received response: PONG for request ID: b733d7bc-d98b-426e-8e9a-9f78d6e93002
2024-11-06 10:51:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:50 - INFO - client: Received response: PONG for request ID: d5ecf22e-f17c-43ed-a9e1-e5f8854e191f
2024-11-06 10:51:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:50 - INFO - client: Received response: 6246 for request ID: 979f1170-997e-4f38-b72b-801f66b65cb9
2024-11-06 10:51:50 - INFO - client: Received response: 4626 for request ID: 531a072f-c328-4957-81d4-e15ca9ebfddf
2024-11-06 10:51:50 - INFO - client: Received response: PONG for request ID: f049c766-72c6-4e4a-899f-d02ea34be17a
2024-11-06 10:51:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:50 - INFO - client: Received response: PONG for request ID: 1923abb1-b4db-4d67-a692-c523a2a81a58
2024-11-06 10:51:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:54 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:54 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 10:51:54 - INFO - client: Received response: PONG for request ID: 4b082d00-5bcb-4b8e-9a76-45608199cdc6
2024-11-06 10:51:54 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:51:54 - INFO - client: Received response: PONG for request ID: 13d9d145-8385-45e7-b018-1131e05db29b
2024-11-06 10:51:54 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 10:52:00 - INFO - client: Sent request: 3 with delay: 0.0 sec
2024-11-06 10:52:00 - INFO - client: Received response: 6 for request ID: 4182ab66-51d0-4a4f-96bf-39c69aa0ede4
2024-11-06 10:52:01 - INFO - client: Sent request: 3 with delay: 0.0 sec
2024-11-06 10:52:01 - INFO - client: Received response: 6 for request ID: 36ef94fd-630f-48f2-9d21-cff125010960
2024-11-06 10:52:03 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 10:52:03 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 10:52:03 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75e6feee9300> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 10:52:03 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56560), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 10:52:03 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56560), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:03 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56560), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:03 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:03 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-06 10:52:03 - CRITICAL - pika.connection: Received METHOD frame for unregistered channel 1 on <SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 10:52:03 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:03 - ERROR - pika.connection: Illegal close(200, 'Normal shutdown') request on <SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> because it was called while connection state=CLOSED.
2024-11-06 10:52:03 - ERROR - client: Error closing connection: Illegal close(200, 'Normal shutdown') request on <SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> because it was called while connection state=CLOSED.
2024-11-06 10:52:03 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56560), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:03 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:03 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 10:52:04 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 10:52:04 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34996), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 10:52:04 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.50e9339817504caebd4d5c1b7329c435'])>"])>
2024-11-06 10:52:04 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34996), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:04 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34996), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:04 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:04 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 10:52:04 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-06 10:52:04 - ERROR - client: Error closing connection: 'NoneType' object has no attribute 'write'
2024-11-06 10:52:04 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:04 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 34996), raddr=('127.0.0.1', 5672)>
2024-11-06 10:52:04 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 10:52:04 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 11:03:35 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:03:35 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51786), raddr=('127.0.0.1', 5672)>
2024-11-06 11:03:35 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e29971dd270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e29971dd270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:03:35 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e29971dd270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:03:35 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e29971dd270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:03:35 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7e29971dd270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:03:35 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:03:35 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-ILTdKTaLOuqKV4uUoyqizw
2024-11-06 11:03:35 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:03:35 - INFO - client: Received response: PONG for request ID: 5a6f7f2a-e461-4f5a-932d-fbf0debf8072
2024-11-06 11:03:35 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:06:28 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:06:28 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 46054), raddr=('127.0.0.1', 5672)>
2024-11-06 11:06:28 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x70c9ec1e5270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x70c9ec1e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:06:28 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x70c9ec1e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:06:28 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x70c9ec1e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:06:28 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x70c9ec1e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:06:28 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:06:28 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-86FX0zjIPjFUycw-TCdPqg
2024-11-06 11:06:28 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:06:28 - INFO - client: Received response: PONG for request ID: bc0cd98e-5395-4208-859d-6d555909262a
2024-11-06 11:06:28 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:11:05 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:11:05 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58094), raddr=('127.0.0.1', 5672)>
2024-11-06 11:11:05 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7896ac9e5270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7896ac9e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:11:05 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7896ac9e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:11:05 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7896ac9e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:11:05 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7896ac9e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:11:05 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:11:05 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-ZBKTEFpYS-wG2OxGDl-9SA
2024-11-06 11:11:05 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:11:05 - INFO - client: Received response: PONG for request ID: 88ae1b28-57e3-49f1-ac43-3ac2b78d716e
2024-11-06 11:11:05 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:12:27 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:12:27 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60642), raddr=('127.0.0.1', 5672)>
2024-11-06 11:12:27 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x729ea83e5270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x729ea83e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:12:27 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x729ea83e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:27 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x729ea83e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:27 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x729ea83e5270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:27 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:12:27 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-g9sn6nKIs2AvF4Dbq4weGg
2024-11-06 11:12:27 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:12:27 - INFO - client: Received response: PONG for request ID: 02fe19da-3029-4918-b4ba-e39e95ab343a
2024-11-06 11:12:27 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:12:50 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:12:50 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57660), raddr=('127.0.0.1', 5672)>
2024-11-06 11:12:50 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:12:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:50 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:12:50 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:12:50 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-wudAVWIjKChiafNziY0Jug
2024-11-06 11:12:50 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:12:50 - INFO - client: Received response: PONG for request ID: e68f4a4e-e058-4c20-b751-305b9f744f80
2024-11-06 11:12:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:00 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:13:00 - INFO - client: Received response: PONG for request ID: b5a77f3e-b773-4388-a4a1-d24b5b83afae
2024-11-06 11:13:00 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:00 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 11:13:00 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.d07f9fccdbf44693ba549f166cd772f2'])>"])>
2024-11-06 11:13:00 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7413713e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:13:00 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57660), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 11:13:00 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57660), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:00 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57660), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:00 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:00 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-06 11:13:00 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:00 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57660), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:00 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:00 - ERROR - client: Error closing connection: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 11:13:13 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:13:13 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44528), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:13 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:13:13 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:13 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:13 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:13 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:13:13 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-v_vE1BX_rN7UHy0IF_aETg
2024-11-06 11:13:13 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:13:13 - INFO - client: Received response: PONG for request ID: 5ce0ff2e-6bb4-4287-8cba-2487884bb97d
2024-11-06 11:13:13 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:23 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:13:23 - INFO - client: Received response: PONG for request ID: 1fc53f70-06ec-4304-ab7a-b0ae0a85f16e
2024-11-06 11:13:23 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:33 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:13:33 - INFO - client: Received response: PONG for request ID: cbb0613f-378c-4dcf-8028-693756aa5673
2024-11-06 11:13:33 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:37 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 11:13:37 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.03d12f28b2d14104b4127d936a0ebc9c'])>"])>
2024-11-06 11:13:37 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:13:37 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44528), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 11:13:37 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44528), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:37 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x73859ffe9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:13:37 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44528), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:37 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-11-06 11:13:37 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:37 - ERROR - client: Error closing connection: 'NoneType' object has no attribute 'write'
2024-11-06 11:13:37 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-11-06 11:13:37 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:37 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44528), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:37 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:13:37 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 11:13:50 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:13:50 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56704), raddr=('127.0.0.1', 5672)>
2024-11-06 11:13:50 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:13:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:50 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:50 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:13:50 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:13:50 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-K4btDO6KW50s3orMHEupSA
2024-11-06 11:13:50 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:13:50 - INFO - client: Received response: PONG for request ID: a271817b-24e6-4116-b24b-f866ca73875a
2024-11-06 11:13:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:13:55 - INFO - client: Sent request: 2321321312 with delay: 5.0 sec
2024-11-06 11:14:00 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:14:00 - INFO - client: Received response: 4642642624 for request ID: d9b4244c-13f5-4f8d-80bb-4502be042342
2024-11-06 11:14:00 - INFO - client: Received response: PONG for request ID: ca605715-f4b5-4d30-a44a-b8efaa091429
2024-11-06 11:14:00 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:14:10 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 11:14:10 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f19f92e9270> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:14:10 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56704), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 11:14:10 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56704), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:10 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56704), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:10 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:14:10 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-06 11:14:10 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:14:10 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56704), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:10 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:14:10 - ERROR - client: Error closing connection: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 11:14:40 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:14:40 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37998), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:40 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:14:40 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:40 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:40 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:40 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:14:40 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-cYpvcLXFTV6lUMyncAWmCA
2024-11-06 11:14:40 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:14:40 - INFO - client: Received response: PONG for request ID: cdc31bb8-2032-4ca9-a6d0-05be53139808
2024-11-06 11:14:40 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:14:50 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:14:50 - INFO - client: Received response: PONG for request ID: adc919c2-aad9-41e6-9161-c71e602107ea
2024-11-06 11:14:50 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:14:56 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 11:14:56 - INFO - pika.channel: Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:14:56 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x78694ffe52d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-11-06 11:14:56 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-11-06 11:14:56 - INFO - pika.adapters.utils.io_services_utils: Aborting transport connection: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37998), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:56 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37998), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:56 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37998), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:56 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-11-06 11:14:56 - INFO - pika.connection: Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2024-11-06 11:14:56 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=3; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37998), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:56 - INFO - pika.adapters.blocking_connection: User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2024-11-06 11:14:56 - INFO - client: Connection to RabbitMQ closed.
2024-11-06 11:14:59 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:14:59 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 51174), raddr=('127.0.0.1', 5672)>
2024-11-06 11:14:59 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x762a681e12d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x762a681e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:14:59 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x762a681e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:59 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x762a681e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:59 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x762a681e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:14:59 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:14:59 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-Z90c5gGoGiETl0CPyG0TdQ
2024-11-06 11:14:59 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:14:59 - INFO - client: Received response: PONG for request ID: 9f8bf447-23f5-43f1-8a6d-f2a6a19ea8b0
2024-11-06 11:14:59 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:15:09 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:15:09 - INFO - client: Received response: PONG for request ID: 42fca09d-affa-498a-b175-c9aa46bed568
2024-11-06 11:15:09 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:15:33 - INFO - pika.adapters.utils.connection_workflow: Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2024-11-06 11:15:33 - INFO - pika.adapters.utils.io_services_utils: Socket connected: <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60550), raddr=('127.0.0.1', 5672)>
2024-11-06 11:15:33 - INFO - pika.adapters.utils.connection_workflow: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bd1f9e12d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bd1f9e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2024-11-06 11:15:33 - INFO - pika.adapters.utils.connection_workflow: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bd1f9e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:15:33 - INFO - pika.adapters.utils.connection_workflow: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bd1f9e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:15:33 - INFO - pika.adapters.blocking_connection: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x76bd1f9e12d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2024-11-06 11:15:33 - INFO - pika.adapters.blocking_connection: Created channel=1
2024-11-06 11:15:33 - INFO - client: Connected to RabbitMQ and listening on queue: amq.gen-LL3pjVlcfE5NjnLmASvckw
2024-11-06 11:15:33 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:15:33 - INFO - client: Received response: PONG for request ID: 3d1f8e3c-2635-4074-989d-5d757e1cbb5f
2024-11-06 11:15:33 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:15:43 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:15:43 - INFO - client: Received response: PONG for request ID: 52e7e7aa-d2db-40ed-978f-3062442f9454
2024-11-06 11:15:43 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:15:53 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:15:53 - INFO - client: Received response: PONG for request ID: b3d22c79-bb35-451c-82b8-6ca8e0e9d9fe
2024-11-06 11:15:53 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:16:03 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:16:03 - INFO - client: Received response: PONG for request ID: 4400a7a3-7a55-4405-81e6-f940044ed842
2024-11-06 11:16:03 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:16:05 - INFO - client: Sent request: 312312 with delay: 10.0 sec
2024-11-06 11:16:09 - INFO - client: Sent request: 31323 with delay: 10.0 sec
2024-11-06 11:16:13 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:16:13 - INFO - client: Received response: PONG for request ID: 5e0e4ae7-16b2-462c-916d-e3c95bff79b0
2024-11-06 11:16:13 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:16:15 - INFO - client: Received response: 624624 for request ID: 5c03767c-a434-4cd8-8fb7-d82bae8db0f5
2024-11-06 11:16:19 - INFO - client: Received response: 62646 for request ID: 37ce62d2-72aa-4d59-8b3c-4a4c454ab618
2024-11-06 11:16:23 - INFO - client: Sent heartbeat message 'PING' to server.
2024-11-06 11:16:23 - INFO - client: Received response: PONG for request ID: f5f9a255-ac40-4858-a21f-7715b1d9af45
2024-11-06 11:16:23 - INFO - client: Received heartbeat response PONG from server.
2024-11-06 11:16:25 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-11-06 11:16:25 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60550), raddr=('127.0.0.1', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/home/user/Desktop/GUI/venv/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-11-06 11:16:25 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60550), raddr=('127.0.0.1', 5672)>
2024-11-06 11:16:25 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60550), raddr=('127.0.0.1', 5672)>
2024-11-06 11:16:25 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.9ea80a15b9544cf9acd8b393e12e8f4c'])>"])>
2024-11-06 11:16:25 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:16:25 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2024-11-06 11:16:25 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:16:25 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60550), raddr=('127.0.0.1', 5672)>
2024-11-06 11:16:25 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-11-06 11:16:25 - ERROR - client: AMQP Error: Stream connection lost: IndexError('pop from an empty deque')
2024-11-06 11:16:25 - ERROR - client: Error closing connection: Channel is closed.
